# Generated by Django 5.1.3 on 2024-11-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
