# Generated by Django 5.0.7 on 2024-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_image_description_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
